import type { Metadata } from "next";

import { Inter } from "next/font/google";

import Script from 'next/script';

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Agora",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/*<Script src="https://apis.google.com/js/api.js" strategy="lazyOnload" />*/}
        {/*<Script src="/static/scripts/googleAPI.js"></Script>*/}

        {children}
      </body>
    </html>
  );
}
